# Generated by Django 5.2.4 on 2025-11-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenttransaction',
            name='withdrawal_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
