# Generated by Django 5.2.4 on 2025-11-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0002_recenttransaction_withdrawal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenttransaction',
            name='crypto_type',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('TRON', 'Tron'), ('LTC', 'Litecoin')], max_length=10),
        ),
    ]
