# Generated by Django 5.0.1 on 2025-07-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0002_customuser_main_customuser_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
