# Generated by Django 5.2.4 on 2025-12-01 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0003_alter_recenttransaction_crypto_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='kyc_photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='kyc_status',
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
