# Generated by Django 5.0.1 on 2025-07-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0003_customuser_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
    ]
