# Generated by Django 5.2.4 on 2026-03-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0004_remove_customuser_kyc_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='recenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment')], max_length=10),
        ),
    ]
