# Generated by Django 5.2.4 on 2026-03-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0005_alter_recenttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenttransaction',
            name='crypto_type',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('TRON', 'Tron'), ('LTC', 'Litecoin'), ('USDT', 'Usdt')], max_length=10),
        ),
    ]
